### ISSUE TITLE
New release with rust-openssl 0.9 support

### ISSUE THREAD

**Issue by sdroege** [sfackler/rust-openssl-verify#2]
Now that 0.9.0 is out, a new release of openssl-verify would be useful to have too :)

**Comment by sfackler** [comment]
The `SslConnector` type in rust-openssl uses this logic internally when linking against OpenSSL 1.0.1, and OpenSSL's native hostname verification logic when linking against 1.0.2 and 1.1.0, so I didn't think that this crate would need to be updated. Do you need an external implementation specifically?

**Comment by sdroege** [comment]
No, I just noticed that hyper depends on this crate. But once ported to openssl 0.9 and SslConnector/Acceptor this is probably not needed anymore indeed. Thanks and sorry for the noise

**Comment by sfackler** [comment]
No problem!

**Comment by e-oz** [comment]
Cookie, plugin for Iron, has openssl-verify 0.2 in dependencies, it leads to downloading openssl-sys 0.7.17. Meanwhile, other users of openssl-verify, have openssl-sys 0.9.0 in dependencies. These 2 versions can't be compiled simultaneously. Please consider to bump version.

**Comment by e-oz** [comment]
Oops, wrong. Openssl-verify itself have dep openssl-sys 0.7.17 and it's enough for conflict. And openssl-verify is required by Hyper 0.9.11.
