### ISSUE TITLE
Could you update the crate?

### ISSUE THREAD

**Issue by CorruptComputer** [sfackler/rust-openssl-verify#4]
https://crates.io/crates/openssl-verify

Only has up to 0.2.

**Comment by sfackler** [comment]
Is there some reason you can't use `openssl::ssl::SslConnector`? This crate is deprecated in favor of that.

**Comment by CorruptComputer** [comment]
Some dependencies I use rely on this, however I would like to move on to openssl 0.9 and I cannot because they can't update this.

**Comment by sfackler** [comment]
If those dependencies need to be updated, why wouldn't they drop their dependency on this crate when doing that?

**Comment by sfackler** [comment]
If you just need to override the version with a `[replace]` section, the master branch of this repo is updated to support 0.9 so you can point the replace to here.

**Comment by CorruptComputer** [comment]
Well one of the dependencies I am working with is `Hyper`, and I am trying to update it to remove this and add the new one you said. I have also tried just getting the master repo for openssl and it gives the same error:
````
error: failed to run custom build command for `openssl-sys v0.9.6 (file:///C:/Users/ngupton/Desktop/rust-openssl/openssl-sys)`
process didn't exit successfully: `C:\Users\ngupton\Desktop\rust-openssl\target\debug\build\openssl-sys-00bf87b006900447\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=C:\OpenSSL-Win64\lib
cargo:include=C:\OpenSSL-Win64\include\openssl\

--- stderr
thread 'main' panicked at 'failed to open header file at `openssl/opensslv.h` to learn
                    about OpenSSL's version number, looked inside:

[
    "C:\\OpenSSL-Win64\\include\\openssl\\"
]

', C:\Users\ngupton\Desktop\rust-openssl\openssl-sys\build.rs:227
note: Run with `RUST_BACKTRACE=1` for a backtrace.
````

But looking in the openssl folder, that file is there. Why wouldn't it be able to open it?

**Comment by sfackler** [comment]
Use Hyper's 0.10 release and the `hyper-openssl` crates.

It's looking for `C:\OpenSSL-Win64\include\openssl\openssl\opensslv.h` - remove the prefix from the environment variable (or just use `OPENSSL_DIR` rather than `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR`).

**Comment by CorruptComputer** [comment]
Ah, that worked thanks! Is there any upgrade guide or docs about upgrading from this to `openssl::ssl::SslConnector`?

**Comment by sfackler** [comment]
`SslConnector` is designed to do most of the work for you. If you don't need to do anything special, `OpenSslClient::new()` in hyper-openssl should be all you need to do.

**Comment by CorruptComputer** [comment]
Ah, thanks!
